project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!LICENSE.md"
format:
  html:
    theme: 
      light: flatly
      dark: darkly
website:
  title: "CSP (Computer Science Project)"
  page-navigation: true
  sidebar:
    logo: src/logos/DigiPen_Dragon_Shield_RGB_Black.png
    style: "docked"
    collapse-level: 2
    search: true
    contents:
      - text: "CSP (Computer Science Project)"
        href: index.qmd
      - text: "---"
      - section: "Lecture: Introducing AI Agents"
        contents:
          - text: "Slides"
            href: src/00/ai_agents.qmd
            target: blank
          - text: "Resources"
            href: src/00/resources.qmd
      - section: "Lecture: Exploring Generative AI Models (Part 1)"
        contents:
          - text: "Slides"
            href: src/01/exploring_genai_p1.qmd
            target: blank
          - text: "Resources"
            href: src/01/resources.qmd
      - section: "Lecture: Exploring Generative AI Models (Part 2)"
        contents:
          - text: "Slides"
            href: src/02/exploring_genai_p2.qmd
            target: blank
          - text: "Resources"
            href: src/02/resources.qmd
      - section: "Networking Protocols"
        contents:
          - text: "WebSockets"
            href: src/networking/websockets.qmd
          - text: "WebRTC"
            href: src/networking/webrtc.qmd
          - text: "WebRTC using an SFU"
            href: src/networking/webrtc-sfu.qmd
          - text: "HTTP/3"
            href: src/networking/http3.qmd