[project]
name = "csp"
version = "0.1.0"
description = "Demo code and content for DigiPen CSP-3/400 and 3/450 courses"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "quarto-cli>=1.7.31",
]